# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stock Checker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stock Checker
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  pod 'Resolver'
  pod 'Disk', '~> 0.6.4'

  target 'Stock CheckerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stock CheckerUITests' do
    # Pods for testing
  end

end